
[build-system]
requires = ["setuptools"]
build-backend =  "setuptools.build_meta"

[project]
name = "skymodem"
version = "0.2"
description = "Skylink modem implemented in Python. Includes a DSP sublibrary Kuokka and Cython wrap of Skylink protocol."
readme = "README.md"
requires-python = ">=3.8"
authors = [
    {name= "Markus Hiltune", email="markus.hiltunen@aalto.fi"},
    {name= "Topi Räty", email="topi.raty@aalto.fi"},
]
maintainers = [
    {name= "Markus Hiltunen", email="markus.hiltunen@aalto.fi"},
    {name= "Topi Räty", email="topi.raty@aalto.fi"},
]
classifiers = []

dependencies = [
    "porthouse",
    "rocket-fft",
    "ptpython",
    "aiormq",
    "filelock",
    "skyfield",
    "PyYAML",
    "aioserial",
    "pyserial",
    "pyzmq",
    "psycopg2-binary",
]

[project.scripts]
skymodem = "skylink_cython.skymodem.application:main"

[tool.setuptools]
package-dir = {skymodem = "skymodem"}
package-data = { "skymodem" = ["*.json"]}

